### ISSUE TITLE
want to UpdateGraph at every 'T' integration time (ms) when ScanAverage is more than one

### ISSUE THREAD

**Issue by User2587** [WasatchPhotonics/Wasatch.NET#1]
The UpdateGraph() works well when ScanAverage =1. 
If we increase the ScanAverage > 1, the graph updates completely only after (integration time x ScanAverage).
The graph should be shown after every ScanAverage value before its completion , so that user can terminate acquisition whenever required.

**Comment by mzieg** [comment]
Hi, I understand your statement.  However, you are discussing a feature of the WinFormDemo, a sample application which shows the functioning of the WasatchNET application driver.

Therefore, the purpose of the feature you're describing is to demonstrate that the driver is able to perform _internal_ scan averaging if desired.

The way to implement the observable behavior you describe would be to disable scan averaging _in the driver,_ instead pulling each individual spectrum from the driver and then manually graphing and averaging them in the application code.

That is of course straightforward to do, but it would not demonstrate the driver's ability to encapsulate and automate scan averaging, which is the point of the demo application.  Therefore I do not intend to make the requested change at this time.

Nevertheless, thank you and congratulations on being the first person to actually open an issue against Wasatch.NET (so much so that I missed the notification in my email)!  Please continue letting us know if you find problems with the driver and supporting files, and we will do our best to respond in a timely fashion.

**Comment by User2587** [comment]
Thanks for help and i will consider your suggestion.
